### ISSUE TITLE
[Suggestion] Note both variables in the symbolic hypotheses

### ISSUE THREAD

**Issue by rhinopotamus** [VectorPosse/Intro_Stats#11]
This is a general suggestion for any of the modules that deal with hypothesis testing. When we ask students to write the null and alternative hypotheses in symbols, or when we model how to do this, I suggest that we include in the subscript something about both categorical variables. This will help clarify which of the four proportions in the relative frequency table it is that we're comparing.

For instance, in the example in R module 8, we're investigating whether there's an association between smoking and low birth weight. We write the null hypothesis as:
H<sub>0</sub>: p<sub>nonsmoker</sub> - p<sub>smoker</sub> = 0
I'm suggesting that it would be more informative for us to say:
H<sub>0</sub>: p<sub>low,nonsmoker</sub> - p<sub>low,smoker</sub> = 0

**Comment by VectorPosse** [comment]
This is a great idea. It always has been a struggle for students to remember which variable corresponds to the outcome (let alone which condition is the "success" variable for that outcome).

**Comment by rhinopotamus** [comment]
(I'm actually stealing the idea from several of my students who did this in their exams. :) )

**Comment by VectorPosse** [comment]
That's awesome. I love it when ideas bubble up from students!
