### ISSUE TITLE
Language around standard error formula in Rmd 14

### ISSUE THREAD

**Issue by rhinopotamus** [VectorPosse/Intro_Stats#13]
In R module 14, there's a couple of instances of "math-negative" language around formulas:

- Line 50: "Here is the formula that **you'll have to take on faith**:"
- Line 64: "Without values of $p_{1}$ and $p_{2}$, we cannot plug anything into the **ugly** standard error formula above."
- Line 201: "**Unfortunately**, this is a much **uglier** formula than it was for a test for one proportion."

Suggest replacing these with something more positive or at least neutral. Some concrete suggestions, to which I am not wedded:

- Line 50: "Here is the formula, whose derivation is outside the scope of the course:"
- Line 64: "Without values of $p_{1}$ and $p_{2}$, we cannot compute the standard error given by the formula above."
- Line 201: "Remember that, when we compute the z-score, we need to use the formula for the standard error for the two-proportion case than the one for the one-proportion case."

**Comment by VectorPosse** [comment]
Fair enough. On one high, I do want to acknowledge that for students, these formulas can appear intimidating. (To be frank, they are quite ugly.) But it is definitely not my desire to be math-negative, and I appreciate your suggestions for rewording these.
