### ISSUE TITLE
Relabel the code chunks around computation of z-score in Rmd 14

### ISSUE THREAD

**Issue by rhinopotamus** [VectorPosse/Intro_Stats#14]
I think the labeling (and commentary) of the code chunks in lines 182-210ish is a little confusing. 

The code chunk on line 184 computes the standard error, but line 182 says "We also compute a z score". Suggest changing line 182 to say, "Let's compute a z-score. We first need to compute the standard error using the formula from earlier:"

Then, suggest some additional commentary on line 191: "Now that we know the SE, we can compute the z-score in the usual way:"

Line 201 might also be confusing, leading students to believe that there is a different formula for the z-score. Rather, there's just a different formula for the standard error. Suggest changing the last sentence here to something like: "Note that we need to use the new SE formula for the two-proportion case, instead of the one for the one-proportion case."

**Comment by VectorPosse** [comment]
Yes, this makes a lot of sense.
