### ISSUE TITLE
[Suggestion] Manual computation of chi-square in Rmd 15

### ISSUE THREAD

**Issue by rhinopotamus** [VectorPosse/Intro_Stats#15]
In Rmd 15, about line 92, suggest replacing:

\chi^{2} = \frac{(11 - 10.67)^{2}}{10.67} + \frac{(7 - 10.67)^{2}}{10.67} + \frac{(14 - 10.67)^{2}}{10.67} = 2.3.

with 

\chi^{2} = \frac{(11 - 10.67)^{2}}{10.67} + \frac{(7 - 10.67)^{2}}{10.67} + \frac{(14 - 10.67)^{2}}{10.67} \approx 2.312.

Students might otherwise be confused as to why the value that was computed manually differs from the value computed by `chisq`.

**Comment by VectorPosse** [comment]
Yes, that's a good idea.
