### ISSUE TITLE
[Question] Symbolic H_A for chi-square test

### ISSUE THREAD

**Issue by rhinopotamus** [VectorPosse/Intro_Stats#16]
In the example chi-square test of goodness-of-fit for cylinders of cars from the mtcars data set: Is there any particular reason why we couldn't write
H_A: p_4 \neq p_6, p_4 \neq p_8, or p_6 \neq p_8 ?

This would generalize nicely to the case where we're comparing to a given probability distribution, as in the "Your turn:"
H_0: p_{general} = .15, p_{academic} = .6, p_{vocational} = .25 (we're implying an "and" here)
H_A: p_{general} \neq .15, p_{academic} \neq .6, p_{vocational}, \neq .25 (implied "or")

I suspect that there might just be some subtlety here that I'm not understanding. Is it just to avoid the "and" vs. "or" thing?

**Comment by VectorPosse** [comment]
Yes, it's the and/or thing. The idea is that some of the categories may indeed take their null values, but if even one doesn't, you still reject the null. (Of course, if one doesn't, then at least two don't, but that's beside the point.)
