### ISSUE TITLE
Module 15: have a non-uniform null in the example

### ISSUE THREAD

**Issue by rhinopotamus** [VectorPosse/Intro_Stats#26]
This is another one of those issues that seems to cause a lot of confusion for students. Suggestion: Make the first example a non-uniform distribution, then have a little section that says "What if the null *is* a uniform distribution?" This will generalize better, because then it makes more sense that the percentages should be 33, 33, 33 or whatever, and then we can talk about how the default is to think about the data being evenly split across categories.

Another benefit is that it would better match the presentation in the book, where the primary example is a nonuniform distribution.

**Comment by VectorPosse** [comment]
Yes, this makes a lot of sense.
