### ISSUE TITLE
suppress messages from library(.)

### ISSUE THREAD

**Issue by nerdcommander** [VectorPosse/Intro_Stats#29]
It bothers me that all of the messages and warnings from libarary-ing packages at the beginning of an Rmd file end up in the final knit document so a typical code chunk from a knit document looks like this:  
<pre>```{r libraries, warning=F, message=F}
library(ggplot2)
library(tidyr)
library(mosaic)
```
</pre>

but the notebooks are pretty twitchy about including the messages - some extra hammering leads me to the (possibly ill formed) conclusion that the very first time you library the package it will include the messages etc. but if you run it a second time it goes away. I hate having to skip all that blag all the time, so I googled up this post of several ideas, none for notebooks:  
https://stackoverflow.com/questions/13090838/r-markdown-avoiding-package-loading-messages 

so now I see 2 options, first (leaves the messages in the Rmd output but hides it from the html):
<pre>
```{r libraries, results='hide'}
library(ggplot2)
library(tidyr)
library(mosaic)
```
</pre>
and second (which also hides it from the Rmd output when running the chunk):
<pre>
```{r libraries, results='hide', message=F}
library(ggplot2)
library(tidyr)
library(mosaic)
```
</pre>

I prefer the first for now since the user still sees the occasionally useful messages in the Rmd window but I don't have to see them in student assignments.

MmmmKay?

**Comment by VectorPosse** [comment]
This is a good idea. No need for students to have to wade through all that nonsense.

**Comment by VectorPosse** [comment]
Fixed by adding `warning = FALSE` to the chunk header in all modules.
