### ISSUE TITLE
Module 5: select command is sometimes masked

### ISSUE THREAD

**Issue by VectorPosse** [VectorPosse/Intro_Stats#30]
In module 5, if the student loads packages in a funky order, the select command might be attempting to access the one from the MASS package instead of dplyr.

**Comment by VectorPosse** [comment]
If students create a new project like they're supposed to and Run All right away, this should never be a problem. I'm debating if it's more confusing than helpful to replace `select` with `dplyr::select` everywhere. Alternatively, maybe `detach("package:MASS")` (or possibly `detach("package:MASS", unload=TRUE)`--I need to investigate this command) would be less obtrusive.

**Comment by nerdcommander** [comment]
I think the "new project, run all" reminder is at least a good patch...
