### ISSUE TITLE
making a factor and other code should be in separate chunks

### ISSUE THREAD

**Issue by nerdcommander** [VectorPosse/Intro_Stats#31]
I had a bunch of students struggle with making a factor (probably no surprise) but then the fact that the code to make the factor and code to assign it to something else are in the same chunk caused additional issues. For example, in module 04_Categorical_data.Rmd, the example using `factor()` is:
```{r}
race <- factor(birthwt$race,
               levels = c(1, 2, 3),
               labels = c("White", "Black", "Other"))
race_df <- data.frame(race)
```
I'm recommending that we split this into 2 separate code chunks for 2 reasons.  
1. error messages can be uninformative. several students were getting errors like "object race not found" but the real problem was that they stuffed up their `factor()` code so there was no vector called `race` for the assignment to find. If the chunks are separate they would get an error about the factor() code, which is what was broken 97.547865% of the time. (really the issue isn't this example, but when students copy paste and adapt)
2. several students conflated these 2 different lines of code and would change the `factor()` part and not the bottom part, or they would always include this part: `race_df <- data.frame(race)` even when they wanted to do somethings else. They thought you had to do all of it no matter what.

the explanation of the pieces is already all there, I'd just separate the code and explanations.

**Comment by VectorPosse** [comment]
Yes, this makes a lot of sense.
