### ISSUE TITLE
date stamp for notebooks (and other Rmd files that are knit)

### ISSUE THREAD

**Issue by nerdcommander** [VectorPosse/Intro_Stats#32]
by googling my brains out, I found that if you use the date line below in the YAML header, it stamps the date and time of preview/knitting. 
```
date: "`r format(Sys.time(), 'on %a %b %d, %Y, at %H:%M:%S')`" 
```
I like it, even just for myself, since it tells you the most recent preview/knit right in the output.
Maybe something for future versions of the modules for students?

**Comment by VectorPosse** [comment]
I'm debating between the ease of pre-populating the date field and the possibility of giving students yet something else they can touch and mess up. And diagnosing YAML header errors is much more challenging. So I'm conflicted about this one.

**Comment by nerdcommander** [comment]
Definitely get what you're saying! Mostly I just thought it was slick.

**Comment by nerdcommander** [comment]
one other advantage in my grading system where students resubmit, the stamp updates when they preview a new submission and we all can keep track of newest version. minor thing and not a care if resubmission isn't a thing you do.

**Comment by VectorPosse** [comment]
Doesn't Canvas track resubmissions?

**Comment by VectorPosse** [comment]
I think I've decided not to incorporate this suggestion. I think the pain of getting errors coming from the YAML header will be too great.
