### ISSUE TITLE
Module #7- Simulation values no longer agree with text below

### ISSUE THREAD

**Issue by VectorPosse** [VectorPosse/Intro_Stats#34]
Somehow the behavior of `set.seed()` has changed so that the random numbers in `sims` no longer agree with the expository text below.

**Comment by nerdcommander** [comment]
oh, snap! how true...

**Comment by VectorPosse** [comment]
Actually, it's not `set.seed()`. It is this:

https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17494

**Comment by VectorPosse** [comment]
This will also require re-computation of all P-values in the modules involving simulation due to `sample()` (and therefore `shuffle()` and `rflip()`) being affected.

**Comment by VectorPosse** [comment]
This has been fixed.
