### ISSUE TITLE
adding geom_qq_line() to qq plots

### ISSUE THREAD

**Issue by nerdcommander** [VectorPosse/Intro_Stats#35]
a suggestion: can we add geom_qq_line() to all of the example qq plots? I have been asking my students to do this and at least some of them are more aware of patterns in the qq_plot since the y=x line is much more obvious -- for example deviations in the slope and tails are more obvious.
(PS I don't know if you remember how obsessed I got with these lines a few years ago, before geom_qq_line() existed but I'm simultaneously excited that it exists and a bit let down that it is now so easy. When I was a boy, we had to make ours by hand...)
just a thought...

**Comment by VectorPosse** [comment]
I did not know it existed! Yes, quite happy to add the lines.
