### ISSUE TITLE
Module 4: Some birthwt variables are not *very* numeric

### ISSUE THREAD

**Issue by rhinopotamus** [VectorPosse/Intro_Stats#40]
In R module 4 exercise 7, we ask students to pick one numerical and one categorical variable and draw some plots. Both `ptl` and `ftv` are *sorta* numerical but do not take on very many different values, and so they end up being poor choices for the purposes of this exercise -- they behave much more like categorical variables than numerical variables. Perhaps we should warn students away from choosing `ptl` or `ftv` for Exercise 7.

**Comment by VectorPosse** [comment]
Yep. Makes sense.
