### ISSUE TITLE
Module 04 rubric edit

### ISSUE THREAD

**Issue by jonasdandrea** [VectorPosse/intro_stats#44]
Module 04, Question 4a answer in the rubric lists % of white women who smoke during pregnancy as 52.4%.  Should be 54.2% I think.

Might be worth leaving as check on rubric copying, as long as QUARC consultants know about it.

**Comment by VectorPosse** [comment]
Actually, that whole module will be changed in the upcoming edits anyway.

**Comment by VectorPosse** [comment]
With the newest version, this issue will be moot.
