### ISSUE TITLE
R module #4 exercise 8 -- no previous example of labeling "fill"

### ISSUE THREAD

**Issue by rhinopotamus** [VectorPosse/Intro_Stats#5]
In R module 4, Exercise 8 asks:
"Modify the following side-by-side bar chart by adding a title and labels for both the fill variable and the x-axis variable."
We've previously seen examples of adding labels for the x-axis and y-axis variables, but not the fill variable. It's reasonable enough for students to guess that the required command should indeed be
`labs(..., fill="desired label")`
but perhaps we want to give them a more explicit example, or else clue them in explicitly that "fill" is a thing you can tell `labs` about.

**Comment by VectorPosse** [comment]
Yep, this could be more clear. (Students usually manage to figure this out, but we should be explicit.)
