### ISSUE TITLE
Suggestion: prompt students to remove penguins with NA body mass

### ISSUE THREAD

**Issue by rhinopotamus** [VectorPosse/intro_stats#58]
Okay, so there's 344 penguins in the `penguins` dataset. But two of them have NA body mass. This causes the following issues:

- `penguins %>% group_by(species) %>% summarize(mean(body_mass_g))` will fail unless `, na.rm = TRUE` is added
- students might report the wrong sample sizes
- and thus students might be confused by the df calculations that `infer` does: df_E = n - k, which students will probably want to compute as 344 - 3 = 341. But secretly n = 342, so df_E = 342 - 3 = 339.
- `infer` will throw warnings about removing 2 rows. (But maybe students don't look at that / don't know what that means.)

Suggestion: let's prompt students in the "Your turn" setup to filter out the penguins with NA body mass. I'm not sure we have shown them how to do this before, so we may even want to provide `%>% filter(!is.na(...))` as a hint. 

Happy to take a stab at this if you think it'd be good.

**Comment by VectorPosse** [comment]
Ah, crap. Okay, I have a second to look at this right now. I'll get back to
you.

**Comment by VectorPosse** [comment]
It was an easy fix with

```
penguins2 <- penguins %>%
  drop_na(species, body_mass_g)
```

**Comment by VectorPosse** [comment]
I'm currently re-building (which, now that the book is basically complete, takes friggin' forever).

**Comment by rhinopotamus** [comment]
I always forget about `drop_na`, lol
