### ISSUE TITLE
Module 5: slightly confusing directions in Exercise 1

### ISSUE THREAD

**Issue by rhinopotamus** [VectorPosse/Intro_Stats#7]
It's not quite clear how to get the help page for `hflights` to show up in the Help window if we haven't already loaded the `hflights` package with `library(hflights)`. Some suggested fixes:

- Tell students to look in the Packages tab instead of in the Help tab
- Tell students to do `library(hflights)` and then `?hflights` in the console
- Tell students to put `hflights` in the search box in the Help tab and look through the resulting list of possible results to find the one they want

**Comment by VectorPosse** [comment]
Makes sense. Given that we're having students download the file (and, in general, files downloaded from the internet will not come with help files), I may end up just reproducing the relevant bits of the help file in the notebook. Or maybe I'll put the help file on its own webpage hosted in the same location as the data and just include a link.
