### ISSUE TITLE
Suggestion for Module 5 exercise 3

### ISSUE THREAD

**Issue by rhinopotamus** [VectorPosse/Intro_Stats#8]
Several students have noted that the four variables we've asked them to remove are contiguous and at the beginning of the list. That means that they could use the colon notation again and write `hf_select4 <- select(hf, DepTime:Diverted)` and end up with the same dataframe produced by the
 nominally correct answer `hf_select4 <- select(hf, -Year, -Month, -DayofMonth, -DayOfWeek)`.

Thus, suggest asking students to remove four variables that aren't in a contiguous block in the dataset.

**Comment by VectorPosse** [comment]
This whole assignment will undergo wholesale revision, so assuming this exercises survives the process, I think it makes sense to think carefully about which variables we should have students extract.

**Comment by VectorPosse** [comment]
This got fixed along the way. I chose a non-contiguous set of columns.
